### ISSUE TITLE
API Integration:

### ISSUE THREAD

**Issue by designs-by-kate** [reececorkhill/Guess-The-Movie#3]
- [x] Implement Movie Database API integration.
- [x] Create functions to fetch random movies and additional information from Movie database API.

**Comment by reececorkhill** [comment]
API implemented in eefb116f167a5155f033da55c954f4fc7f05f65b

**Comment by reececorkhill** [comment]
Both the OMDB and Giphy API's have been implemented. 

Closing issue.
