### ISSUE TITLE
Implement progress bar:

### ISSUE THREAD

**Issue by designs-by-kate** [reececorkhill/Guess-The-Movie#8]
- [x] Create a progress bar component in the user interface.
- [x] Develop functions to update the progress bar based on the user’s progress through the game.

**Comment by reececorkhill** [comment]
This has been added to a ticket on Trello.

In-progress.

**Comment by designs-by-kate** [comment]
Implemented a progress bar component in the user interface and developed functions to dynamically update it based on the user's progress throughout the game. Additionally, the game now finishes when the progress bar reaches 100%. 
**Closing the issue as completed.**
